name: Elm Review

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  elm-review_lint:
    runs-on: self-hosted

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Sparse-Checkout review repository with script
      run: ./.github/elm-review-pltp.sh

    - run: yarn --frozen-lockfile

    - name: Add elm tools to PATH
      run: yarn global bin >> $GITHUB_PATH

    - name: Run elm-review
      uses: sparksp/elm-review-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        elm_review: elm-review
