name: Elm Format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
jobs:
  elm-format_validate:
    runs-on: self-hosted

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - run: yarn --frozen-lockfile

    - name: Add elm tools to PATH
      run: yarn global bin >> $GITHUB_PATH

    - name: Run elm-format
      run: elm-format --validate src/ | jq 'map("::error file=" + .path + "::" + .message) | length > 0 and error("\n" + join("\n"))'
